### PR TITLE
Fix Wisconsin spelling mistake

### PR DESCRIPTION
**Pull request by jpchip**
Fix spelling of Wisconsin and link to corresponding zip file

### CODE REVIEW

**Comment by nitrif** [comment]
We have to rename the file on Azure.

**Comment by jpchip** [comment]
The link actually didn't work with the wisconson spelling, so I don't think you need to change anything?

**Comment by jharpster** [comment]
It's likely just a spelling issue some place. I'll get it sorted.

**Comment by nitrif** [comment]
Thanks!

**Pull request merged**
